---
- name: Include YUM repo information
  include_vars: '../vars/yum.yml'

- name: Install Postgresql YUM repo
  package: name={{ yum_repo_url }} state=present

- set_fact:
    postgresql_enablerepo: 'pgdg{{ postgres_repo_version|regex_replace("\.","") }}'
    __postgresql_version: '{{ postgres_repo_version }}'
    __postgresql_packages:
        - 'postgresql{{ postgres_repo_version|regex_replace("\.","") }}'
        - 'postgresql{{ postgres_repo_version|regex_replace("\.","") }}-server'
        - 'postgresql{{ postgres_repo_version|regex_replace("\.","") }}-contrib'
        - 'postgresql{{ postgres_repo_version|regex_replace("\.","") }}-libs'
